name: Continuous Delivery
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build front end
    steps:

    - name: Make directory
      run: mkdir -p deploy

    - name: Get code
      uses: actions/checkout@v2
      with:
        ref: "master"

    - name: Build frontend
      run: |
        npm install
        npm audit fix
        npm run build
        cp -r ./dist deploy/

    - name: Name artifact
      uses: actions/upload-artifact@v2
      with:
        name: rs_ui
        path: deploy/

  deploy:
      runs-on: ubuntu-latest
      name:  Deploy artifact to Digital Ocean
      needs: build
      steps:

      - name: Download uploaded binary
        uses: actions/download-artifact@v1
        with:
          name: rs_ui

      - name: Transfer with SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: rs_ui
          target: ${{ secrets.WORKDIR }}

      - name: Example command via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: "ls ${{ secrets.WORKDIR }}"
